# Generated by Django 2.0.7 on 2019-09-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='company',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='name',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='auth',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.AddField(
            model_name='lead',
            name='requestor',
            field=models.CharField(default=-1, max_length=500),
            preserve_default=False,
        ),
    ]
