# Generated by Django 2.0.7 on 2019-09-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20190913_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='resource',
        ),
    ]
