# Generated by Django 2.0.7 on 2019-09-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_remove_lead_resource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='media',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='requestor',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='token',
        ),
        migrations.AddField(
            model_name='lead',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
