# Generated by Django 2.0.7 on 2019-09-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20190913_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='current',
            field=models.CharField(default=-1, max_length=100),
            preserve_default=False,
        ),
    ]
