# Generated by Django 2.0.7 on 2019-09-14 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_usermetadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usermetadata',
        ),
    ]
