# Generated by Django 2.0.7 on 2019-09-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20190916_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
